homeassistant:
  name: Noobres Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 676
  unit_system: metric
  time_zone: America/Sao_Paulo
  customize: !include_dir_merge_named custom
  
#---------------------Componentes Diversos-------

config:

logger:

updater:
  include_used_components: true

history:

logbook:
  include:
    domains:
      - switch
      - automation
      - script
      - light

sun:

map:

discovery:

#---------------------Xiaomi----------------------

xiaomi_aqara:
  discovery_retry: 10
  gateways:
   - mac: 34CE00813667
     key: !secret xiaomi

#---------------------HTTP------------------------

http:
  api_password: !secret http_senha
  trusted_networks:
   - 127.0.0.1
   - 192.168.2.0/24
  server_port: 80
  base_url: !secret httpurl
  
#---------------------Metereologia----------------

weather:
  - platform: yweather

#---------------------Telegram--------------------

telegram_bot:
  - platform: polling
    api_key: !secret telegram
    allowed_chat_ids:
      - !secret telegram_chat_dedy
      - !secret telegram_chat_elida
  - platform: broadcast
    api_key: !secret telegram
    allowed_chat_ids:
      - !secret telegram_chat_dedy
      - !secret telegram_chat_elida
  - platform: webhooks
    api_key: !secret telegram
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_chat_dedy  
      - !secret telegram_chat_elida      

#---------------------Thinger---------------------

thingspeak:
  api_key: !secret thing1
  id: 368190
  whitelist: sensor.potencia_ar
  
#---------------------MQTT------------------------

mqtt:
  discovery: true
  broker: 192.168.2.55
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass
  keepalive: 60

#---------------------Device Track----------------

device_tracker:
 - platform: ping
   hosts:
     leeco: 192.168.2.20
     s4: 192.168.2.22
   count: 10
 - platform: owntracks_http
 
#---------------------Econcms History------------

emoncms_history:
  api_key: !secret econ
  url: https://emoncms.org
  inputnode: 19
  whitelist:
    - sensor.cpu_temperature
    - sensor.tensao_ar
    - sensor.potencia_ar

#---------------------Weblinks--------------------

panel_iframe:
  roteador:
    title: Roteador
    url: 'http://192.168.2.1'
    icon: mdi:router-wireless
  cozinha:
    title: Sonoff Luz Cozinha
    url: 'http://192.168.2.68'
    icon: mdi:responsive
  sala:
    title: Sonoff Luz Sala
    url: 'http://192.168.2.90'
    icon: mdi:responsive
  casal:
    title: Sonoff Luz Quarto Casal
    url: 'http://192.168.2.65'
    icon: mdi:responsive
  filho:
    title: Sonoff Luz Quarto Filho
    url: 'http://192.168.2.92'
    icon: mdi:responsive
  sacada:
    title: Sonoff Luz Quarto Sacada
    url: 'http://192.168.2.91'
    icon: mdi:responsive

#---------------------Google----------------------

#---------------------System Log------------------

system_log:
  max_entries: 100


#---------------------TTS-------------------------

tts:
  - platform: google
    cache: true
    time_memory: 300

#---------------------IFTTT-----------------------

ifttt:
  key: !secret ifttt

#---------------------Includes--------------------

group: !include config/grupos.yaml

automation: !include_dir_merge_list automation

history_graph: !include_dir_merge_named graficos

script: !include_dir_merge_named scripts

switch: !include config/switch.yaml

input_boolean: !include config/input_bool.yaml

sensor: !include_dir_list sensores

binary_sensor: !include_dir_list sensores_binarios

input_select: !include config/select.yaml

input_number: !include config/numeros.yaml

zone: !include config/locais.yaml

camera: !include_dir_list cameras

input_text: !include config/textos.yaml

android_ip_webcam: !include_dir_merge_named android_cam

light: !include_dir_merge_list lights

notify: !include config/notificacoes.yaml

#-------------------------------------------------

