default_view:
  name: Noobres Home
  view: true
  icon: mdi:home
  entities:
    - group.grp_06
    - group.grp_09
    - group.grp_11
    - group.grp_13
#    - group.grp_15
    - group.grp_17
#    - group.grp_07
    - group.grp_16
    - group.grp_14
    - group.grp_20
#    - group.grp_21
#    - group.grp_23
    - group.grp_24
    - group.grp_25_1