- platform: mqtt
  name: "Iluminação Cozinha"
  payload_on: "ON"
  payload_off: "OFF"
  state_topic: "stat/cozinha-luz/POWER"
  command_topic: "cmnd/cozinha-luz/POWER"
  qos: 1
  retain: true
  icon: mdi:television-classic
  
- platform: mqtt
  name: "Iluminação Sala"
  payload_on: "ON"
  payload_off: "OFF"
  state_topic: "stat/luz-sala/POWER2"
  command_topic: "cmnd/luz-sala/POWER2"
  qos: 1
  retain: true
  icon: mdi:television-classic 
  
- platform: mqtt
  name: "Iluminação Corredor"
  payload_on: "ON"
  payload_off: "OFF"
  state_topic: "stat/luz-sala/POWER1"
  command_topic: "cmnd/luz-sala/POWER1"
  qos: 1
  retain: true
  icon: mdi:television-classic
  
- platform: mqtt
  name: "Iluminação Quarto Casal"
  payload_on: "ON"
  payload_off: "OFF"
  state_topic: "stat/luz-casal/POWER"
  command_topic: "cmnd/luz-casal/POWER"
  qos: 1
  retain: true
  icon: mdi:television-classic