#--------------------------------------------------------
# - grp_01 = iluminacao interna
# - grp_02 = dados da tomada medicao geral
# - grp_03 = conjunto de automações
# - grp_04 = scripts
# - grp_05 = conjunto de switchs
# - grp_06 = relogio (time)
# - grp_07 = controle de ações teste script
# - grp_08 = controle carregador relogio
# - grp_09 = localização
# - grp_10 = cameras
# - grp_11 = medicoes do sistema
# - grp_12 = xiaomis
# - grp_13 = tempo
# - grp_14 = status dispositivos
# - grp_15 = controle diversos
# - grp_16 = bateria dos telefones
# - grp_17 = rede
# - grp_18 = controle lampada fundo
# - grp_19 = controle tv
# - grp_20 = status telefone
# - grp_21 = sensor binarios tipo trend
# - grp_22 = calendario todoist
# - grp_23 = entrada de textos
# = grp_24 = extensao broadlink
# - grp_25 = graficos
# - grp_26 = mapas
# - grp_27 = ar condicionado

default_view:
  name: Noobres Home
  view: true
  icon: mdi:home
  entities:
    - group.grp_06
    - group.grp_09_01
    - group.grp_09_02
    - group.grp_11
    - group.grp_13
    - group.grp_17
    - group.grp_16
    - group.grp_14
    - group.grp_20
    - group.grp_24
    - group.grp_25_1
    - group.grp_12_5
    - group.grp_27

#-------------------------------------------------------

interr:
  name: switchs
  view: true
  icon: mdi:power-socket
  entities:
    - group.grp_05
    
#------------------------------------------------------
    
scrip:
  name: Scripts
  view: true
  icon: mdi:script
  entities:
    - group.grp_04_1
    - group.grp_04_2
    - group.grp_04_3
    - group.grp_04_4
    - group.grp_04_5

#-------------------------------------------------------

iluminacao:
  name: Controle Iluminação
  view: true
  icon: mdi:lightbulb-on
  entities:
    - group.grp_01_1
    - group.grp_01_2
    - group.grp_01_3
    - group.grp_18
    
#-------------------------------------------------------

medicoes_xia:
  name: Medições Ambiente
  view: true
  icon: mdi:home-assistant
  entities:
    - group.grp_12_1
    - group.grp_12_2
    - group.grp_12_3
    - group.grp_12_4
    
#-------------------------------------------------------

monit:
  name: Monitoramento
  view: true
  icon: mdi:home-assistant
  entities:
    - group.grp_25_1
    - group.grp_25_2
    - group.grp_25_3
    - group.grp_25_4
    
#-------------------------------------------------------    

tv_control:
  name: Controle Midia
  view: true
  icon: mdi:television-classic
  entities:
    - group.grp_19_01
    - group.grp_19_02
    - group.grp_19_03

#-------------------------------------------------------

maps:
  name: Mapas
  view: true
  icon: mdi:google-maps
  entities:
    - group.grp_26_1
    - group.grp_26_2
    - group.grp_26_3
    - group.grp_26_4
    
#-------------------------------------------------------

web_cam:
  name: Controle Web Cam
  view: true
  icon: mdi:webcam
  entities:
    - camera.camera_secundaria

#-------------------------------------------------------  

energia:
  name: Energia
  view: true
  icon: mdi:power-plug
  entities:
    - group.grp_01
    - group.grp_02    
  
#-------------------------------------------------------  

autos:
  name: Automações
  view: true
  icon: mdi:auto-upload
  entities:
    - group.grp_03_01
    - group.grp_03_02
    - group.grp_03_03
    - group.grp_03_04
    - group.grp_03_05
    - group.grp_03_06
   
#-------------------------------------------------------    

disp:
  name: Status Dispositivos
  view: true
  icon: mdi:network
  entities:
    - group.grp_14

#------------------------------------------------------- 

task:
  name: Tarefas Domésticas
  view: true
  icon: mdi:home-outline
  entities:
    - group.grp_22

#-------------------------------------------------------

grp_01_1:
  name: Iluminação Interna
  view: false
  entities:
    - light.iluminacao_cozinha
    - light.iluminacao_sala
    - light.iluminacao_corredor
    - light.iluminacao_quarto_casal
    - light.iluminacao_quarto_filho
    
grp_01_2:
  name: Iluminação Externa
  view: false
  entities:
    - light.iluminacao_sacada

grp_01_3:
  name: Controle Iluminação
  view: false
  entities:
    - sensor.tempo_control_casal
    - sensor.tempo_control_filho
    - sensor.tempo_control_corredor
    - sensor.tempo_control_cozinha
    - sensor.tempo_control_sala
    - sensor.tempo_control_sacada
    - input_number.slid_cont_casal
    - input_number.slid_cont_filho
    - input_number.slid_cont_corredor
    - input_number.slid_cont_cozinha
    - input_number.slid_cont_sala
    - input_number.slid_cont_sacada

#-------------------------------------------------------

grp_02:
  name: Dados Ar Condicionado
  view: false
  entities:
    - sensor.tensao_ar
    - sensor.corrente_ar
    - sensor.potencia_ar
    - sensor.consumo_ar
    - sensor.cons_semanal_ar

#-------------------------------------------------------

grp_03_01:
  name: Automações Diversas
  view: false
  entities:
    - automation.saindo_de_casa
    - automation.chegando_em_casa
    - automation.teste_auto_script
    - automation.testa_bools_01
    - automation.testa_bools_02
    - automation.telegram_bot1
    - automation.dona_home
    - automation.acordando
    - automation.checa_localizacao_dona
    - automation.dona_home
    - automation.dona_not_home
    - automation.localiza_denis
    - automation.localiza_dona
    - automation.localizar_denis
    - automation.localizar_elida
#    - automation.owntracks_refresh
    - automation.saindo_de_casa
    - automation.temperatura_rasp
    - automation.teste_timer

grp_03_02:
  name: Automações Sala
  view: false
  entities:
    - automation.tv_off
    - automation.tv_on
    - automation.volume_lg_
    - automation.volume_lg__2
    - automation.liga_receptor
    - automation.liga_receptor_2
    - automation.liga_tv
    - automation.desliga_receptor
    - automation.desliga_tv
    - automation.temperatura_sala
    - automation.liga_chromecast
    - automation.controle_iluminacao_sala
    - automation.controle_iluminacao_corredor

grp_03_03:
  name: Automações Cozinha
  view: false
  entities:
    - automation.desliga_luz_cozinha
    - automation.liga_luz_cozinha
    - automation.controle_iluminacao_sala
    
grp_03_04:
  name: Automações Quarto Filho
  view: false
  entities:
    - automation.acende_lampada_quarto_casal
    - automation.acende_luz_pedro_henrique
    - automation.apaga_lampada_quarto_casal
    - automation.apaga_luz_pedro_henrique
    - automation.temperatura_quarto_filho
    - automation.controle_iluminacao_quarto_filho

grp_03_05:
  name: Automações Quarto Casal
  view: false
  entities:
    - automation.temperatura_quarto_casal
    - automation.ar_condicionado__desliga
    - automation.ar_condicionado__resfria
    - automation.desliga_ar_condicionado
    - automation.liga_ar_condicionado
    - automation.gelar_quarto
    - automation.habilita_doctor
    - automation.desliga_ar_acordando
    - automation.seta_ar_on
    - automation.seta_ar_off
    - automation.controle_iluminacao_quarto_casal
    
grp_03_06:
  name: Automações Sacada
  view: false
  entities:
    - automation.temperatura_sacada
    - automation.luz_sacada_on
    - automation.luz_sacada_off

#-------------------------------------------------------    

grp_04_1:
  name: Ar Condicionado
  view: false
  control: hidden
  entities:
    - script.scr_gelar
    - script.scr_ar_con_off
    - script.scr_ar_con_on
    
grp_04_2:
  name: Controle TV
  view: false
  control: hidden
  entities:
    - script.scr_set12
    - script.scr_set85
    - script.scr_acordando
    - script.scr_acordando_notifica
    - script.scr_aumenta_volume
    - script.scr_diminui_volume
    - script.scr_set12
    - script.scr_set85
    - script.scr_trabalhar
    - script.scr_vlm_mais
    
grp_04_3:
  name: Diversos
  view: false
  control: hidden
  entities:
    - script.scr_envia_temp_rasp
    - script.scr_liga_luz_01

    
grp_04_4:
  name: Localização
  view: false
  control: hidden
  entities:
    - script.scr_atualiza_dispositivos
    - script.scr_loca_casa
    - script.scr_loca_casa2
    - script.scr_loca_not_casa
    - script.scr_loca_not_casa2
    
grp_04_5:
  name: Iluminação
  view: false
  control: hidden
  entities:
    - script.scr_ctrl_ilm_corredor
    
#-------------------------------------------------------

grp_05:
  name: Interruptores
  view: false
  icon: mdi:dip-switch
  control: hidden
  entities:
    - switch.lgld
    - switch.lgv
    - switch.lgv_2    
    - switch.geladeira
    - switch.tomada_quarto_casal
    - switch.tomada_quarto_filho

#-------------------------------------------------------

grp_06:
  name: Relógio
  view: false
  icon: mdi:timetable
  entities:
    - sensor.time_date
 
#-------------------------------------------------------

grp_07:
  name: Controle de Ações
  view: false
  entities:
    - input_number.slid_tempo_acoes
    - sensor.tempo_acoes
    
#-------------------------------------------------------

#grp_08:
#  name: Control Relogio
#  view: false
#  icon: mdi:watch
#  entities:
#    - sensor.horas_liga_rel
#    - sensor.horas_desliga_rel
#    - input_number.slid_hora_liga
#    - input_number.slid_minuto_liga
#    - input_number.slid_hora_desliga
#    - input_number.slid_minuto_desliga
    
#-------------------------------------------------------

grp_09_01:
  name: Localização Owntracks
  view: false
  icon: mdi:map-marker
  entities:
    - device_tracker.denis_leeco
    - device_tracker.elida_samsung
    
grp_09_02:
  name: Localização Ping
  view: false
  icon: mdi:map-marker
  entities:
    - device_tracker.leeco
    - device_tracker.s4

#-------------------------------------------------------

#grp_10:
#  name: Android Cam
#  view: false
#  icon: mdi:camera
#  entities:
#    - sensor.leeco_cam_audio_connections
#    - sensor.leeco_cam_video_connections
#    - sensor.s5_cam_audio_connections
#    - sensor.s5_cam_video_connections
#    - sensor.tablet_cam_audio_connections
#    - sensor.tablet_cam_video_connections        
    
#-------------------------------------------------------

grp_11:
  name: Sistema
  view: false
  icon: mdi:desktop-classic
  entities:
    - sensor.date
    - sensor.time
    - sensor.disk_use_
    - sensor.ram_free
    - sensor.cpu_use
    - sensor.CPU_Temperature
    - sensor.ha_versao_instalada
    - sensor.ha_versao_disponivel
    - sensor.last_boot
    - sensor.since_last_boot
    - binary_sensor.device_critical
    - binary_sensor.check_temperatura_ha

#-------------------------------------------------------

grp_12_1:
  name: Dados Quarto Casal
  view: false
  entities:
   - sensor.temperature_158d0001d6f829
   - sensor.humidity_158d0001d6f829
   - sensor.pressure_158d0001d6f829
   
grp_12_2:
  name: Dados Quarto Filho
  view: false
  entities:
    - sensor.temperature_158d0001d82815
    - sensor.humidity_158d0001d82815
    - sensor.pressure_158d0001d82815
    
grp_12_3:
  name: Dados Sacada
  view: false
  entities:
    - sensor.temperature_158d0001d82855
    - sensor.humidity_158d0001d82855
    - sensor.pressure_158d0001d82855

grp_12_4:
  name: Dados Sala
  view: false
  entities:
    - sensor.temperature_158d00019c9488
    - sensor.humidity_158d00019c9488   

grp_12_5:
  name: Dados Xiaomi
  view: false
  entities:
    - light.gateway_light_34ce00813667
    - sensor.illumination_34ce00813667
    - binary_sensor.switch_158d00016d7b12
    - script.scr_liga_luz_01  

#-------------------------------------------------------

grp_13:
  name: Tempo
  view: false
  icon: mdi:weather-cloudy
  entities:
  - sensor.yr_temperature
  - sensor.yweather_temperature
  - sensor.yr_humidity
  - sensor.yweather_humidity
  - sensor.yweather_temperature_min
  - sensor.yweather_temperature_max
  - sensor.moon
  - sun.sun
  - weather.yweather
  - sensor.mold_indicator

#-------------------------------------------------------

grp_14:
  name: Status Dispositivos
  view: false
  icon: mdi:television-classic
  entities:
#  - binary_sensor.status_ventilador_home_assistant
#  - binary_sensor.status_carregador_relogio
#  - binary_sensor.status_abajur_pedro_henrique
  - binary_sensor.status_tomada_ar_condidicionado
# - binary_sensor.status_sonoff_sala_tv
  - binary_sensor.Status_Sonoff_sala
  - binary_sensor.Status_Sonoff_cozinha
  - binary_sensor.Status_Sonoff_quarto_casal
  - binary_sensor.Status_Sonoff_quarto_filho
  - binary_sensor.Status_Sonoff_quarto_sacada
  - binary_sensor.status_rm_quarto
  - binary_sensor.status_rm_sala
  - binary_sensor.status_extensao
  - binary_sensor.status_geladeira
  
#-------------------------------------------------------

grp_15:
  name: Comandos
  view: false
  icon: mdi:source-commit-start
  control: hidden
  entities:
#    - counter.ciclo_alarme
    - sensor.total_ciclo
    
#------------------------------------------------------- 

grp_16:
  name: Dados Telefone
  view: false
  icon: mdi:cellphone
  entities:
  - sensor.leeco_bateria
  - sensor.samsung_bateria
  
#-------------------------------------------------------

grp_17:
  name: Status Rede
  view: false
  icon: mdi:access-point-network
  entities:
  - sensor.ipv4_address_eth0
  - sensor.external_ip
  - binary_sensor.Status_Roteador
  - sensor.speedtest_download
  - sensor.speedtest_upload
  - sensor.speedtest_ping
  
#-------------------------------------------------------

grp_18:
  name: Controle Iluminação Externa
  view: false
  icon: mdi:watch
  entities:
    - sensor.horas_liga_fundo
    - sensor.horas_desliga_fundo
    - input_number.slid_hora_liga_fundo
    - input_number.slid_minuto_liga_fundo
    - input_number.slid_hora_desliga_fundo
    - input_number.slid_minuto_desliga_fundo
 
#-------------------------------------------------------

grp_19_01:
  name: Controle TV 01
  view: false
  control: hidden
  entities:
    - sensor.horas_liga_tv
    - sensor.horas_desliga_tv
    - input_number.slid_hora_liga_tv
    - input_number.slid_minuto_liga_tv
    - input_number.slid_hora_desliga_tv
    - input_number.slid_minuto_desliga_tv
    - input_boolean.auto_tv
    
grp_19_02:
  name: Controle TV 02
  view: false
  control: hidden
  entities:
    - script.scr_acordando
    - script.scr_trabalhar
    - script.scr_set12
    - script.scr_set85
    
grp_19_03:
  name: Controle TV 03
  view: false
  control: hidden
  entities:
    - automation.liga_chromecast
    - automation.liga_receptor
    - input_boolean.chrom_auto
    - input_boolean.recept
    - switch.controle_canal
    - switch.controle_volume    
    
#-------------------------------------------------------

grp_20:
  name: Status Smartphones
  view: false
  icon: mdi:map-marker
  entities:
    - binary_sensor.smartphone_leeco
#    - binary_sensor.smartphone_s5
    - binary_sensor.smartphone_s4

#-------------------------------------------------------

grp_21:
  name: Estação Espacial
  view: false
  entities:
    - binary_sensor.iss
    - camera.iss
    
#-------------------------------------------------------

grp_22:
  name: Tarefas Domésticas
  view: false
  entities:
#    - calendar.casa
#    - calendar.inbox
#    - calendar.tarefas
    
#-------------------------------------------------------
grp_23:
  name: Entrada de Textos
  view: false
  entities:
    - input_text.text1
    - input_text.text2

#-------------------------------------------------------

grp_24:
  name: Extensão Broadlink
  view: false
  control: hidden
  entities:
    - switch.receptor
    - switch.chromecast
    - switch.tv_lg
    - switch.reserva

#-------------------------------------------------------

grp_25_1:
  name: Temperatura Quarto Casal
  view: false
  control: hidden
  entities:
    - history_graph.Temperatura_Quarto_Casal
  
grp_25_2:
  name: Temperatura Quarto Filho
  view: false
  control: hidden
  entities:
    - history_graph.Temperatura_Quarto_Filho
    
grp_25_3:
  name: Temperatura Sala
  view: false
  control: hidden
  entities:
    - history_graph.Temperatura_Sala
    
grp_25_4:
  name: Temperatura Sacada
  view: false
  control: hidden
  entities:
    - history_graph.Temperatura_Sacada
    
#-------------------------------------------------------
grp_26_1:
  name: Leeco Map
  view: false
  control: hidden
  entities:
    - camera.leeco

grp_26_2:
  name: Samsung Map
  view: false
  control: hidden
  entities:
    - camera.samsung

grp_26_3:
  name: ISS Map
  view: false
  control: hidden
  entities:
    - camera.iss
grp_26_4:
  name: S5 Map
  view: false
  control: hidden
  entities:
    - camera.s5  

#-------------------------------------------------------

grp_27:
  name: Ar Condicionado
  view: false
  control: hidden
  entities:
    - input_boolean.ctrl_ar_con
    - switch.tomada_ar
    - switch.ar_condicionado_16
    - switch.controle_ar_condicionado
    - switch.ar_condicionado_ventilar
    - switch.ar_condicionado_automatico
    - switch.ar_condicionado_doctor
    - switch.ar_condicionado_turbo