
- name: Apartamento
  latitude: !secret lati_apt
  longitude: !secret long_apt
  radius: 50
#  icon: mdi:home
  
  

- name: Trabalho
  latitude: !secret lati_trab
  longitude: !secret long_trab
#  icon: mdi:work