- alias: Chegando em Casa
  trigger: 
    platform: state
    entity_id: group.grp_09_02
    from: 'not_home'
    to: 'home'
    for:
      hours: 0
      minutes: 3
      seconds: 0
  action:
#    service: script.scr_atualiza_dispositivos
    service: script.scr_acordando
    
- alias: Saindo de Casa
  trigger: 
    platform: state
    entity_id: group.grp_09_02
    from: 'home'
    to: 'not_home'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  action:
    service: script.scr_atualiza_dispositivos
#    service: script.scr_trabalhar
    
- alias: "Owntracks Refresh"
  trigger:
    - platform: time
      minutes: '/3'
      seconds: 0
  action:
    service: script.scr_atualiza_dispositivos
 