
- alias: Luz Sacada On
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.grp_09_02
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: light.turn_on
    entity_id: light.iluminacao_sacada
    
- alias: Luz Sacada Off
  trigger:
    platform: state
    entity_id: group.grp_09_02
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'  
  action:
    service: light.turn_off
    entity_id: light.iluminacao_sacada
      
- alias: Controle Iluminação Quarto Casal
  trigger: 
    platform: state
    entity_id: light.iluminacao_quarto_casal
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - delay: '00:{{ states.sensor.tempo_control_casal.state }}:00'
    - service: light.turn_off
      entity_id: light.iluminacao_quarto_casal
   
- alias: Controle Iluminação Quarto Filho
  trigger: 
    platform: state
    entity_id: light.iluminacao_quarto_filho
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - delay: '00:{{ states.sensor.tempo_control_filho.state }}:00'
    - service: light.turn_off
      entity_id: light.iluminacao_quarto_filho
   
- alias: Controle Iluminação Sala
  trigger: 
    platform: state
    entity_id: light.iluminacao_sala
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - delay: '00:{{ states.sensor.tempo_control_sala.state }}:00'
    - service: light.turn_off
      entity_id: light.iluminacao_sala
   
- alias: Controle Iluminação Corredor
  trigger: 
    platform: state
    entity_id: light.iluminacao_corredor
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - delay: '00:{{ states.sensor.tempo_control_corredor.state }}:00'
    - service: light.turn_off
      entity_id: light.iluminacao_corredor
   
- alias: Controle Iluminação Cozinha
  trigger: 
    platform: state
    entity_id: light.iluminacao_cozinha
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - delay: '00:{{ states.sensor.tempo_control_cozinha.state }}:00'
    - service: light.turn_off
      entity_id: light.iluminacao_cozinha
      
- alias: Controle Iluminação Sacada
  trigger: 
    platform: state
    entity_id: light.iluminacao_sacada
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - delay: '00:{{ states.sensor.tempo_control_sacada.state }}:00'
    - service: light.turn_off
      entity_id: light.iluminacao_sacada
      
- alias: Checa Ferias
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.grp_09_02
    from: 'home'
    to: 'not_home'
    for:
        hours: 16
        minutes: 0
        seconds: 0
  action:
    - service: automation.turn_on
      entity_id: automation.controle_sacada_ferias
      
- alias: Controle Sacada Ferias
  trigger:
    platform: time
    at: '19:50:01'
  action:
    - service: script.turn_on
      entity_id: script.scr_control_sacada
        
  