
- alias: Luz Sacada On
  initial_state: 'on'
  trigger:
    platform: time
    minutes: /20
    seconds: 0
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.grp_09_02
      state: 'not_home'
  action:
    service: light.turn_on
    entity_id: light.iluminacao_sacada
    
- alias: Luz Sacada Off
  trigger:
    platform: state
    entity_id: sun.sun
    from: 'below_horizon'
    to: 'above_horizon'
  action:
    service: light.turn_off
    entity_id: light.iluminacao_sacada
      