
- alias: Luz Sacada On
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.grp_09_02
    from: 'home'
    to: 'not_home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: light.turn_on
    entity_id: light.iluminacao_sacada
    
- alias: Luz Sacada Off
  trigger:
    platform: state
    entity_id: group.grp_09_02
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'  
  action:
    service: light.turn_off
    entity_id: light.iluminacao_sacada
      
- alias: Controle Iluminação Quarto Casal
  trigger: 
    platform: state
    entity_id: light.iluminacao_quarto_casal
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 7
      seconds: 0
  condition:
    - condition: time
      after: '07:00:00'
      before: '19:00:00'
  action:
   service: light.turn_off
   entity_id: light.iluminacao_quarto_casal
   
- alias: Controle Iluminação Quarto Filho
  trigger: 
    platform: state
    entity_id: light.iluminacao_quarto_filho
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 7
      seconds: 0
  condition:
    - condition: time
      after: '07:00:00'
      before: '19:00:00'
  action:
   service: light.turn_off
   entity_id: light.iluminacao_quarto_filho
   
- alias: Controle Iluminação Sala
  trigger: 
    platform: state
    entity_id: light.iluminacao_sala
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 7
      seconds: 0
  condition:
    - condition: time
      after: '07:00:00'
      before: '19:00:00'
  action:
   service: light.turn_off
   entity_id: light.iluminacao_sala
   
- alias: Controle Iluminação Corredor
  trigger: 
    platform: state
    entity_id: light.iluminacao_corredor
    from: 'off'
    to: 'on'
  condition:
    - condition: time
      after: '07:00:00'
      before: '19:00:00'
  action:
    - delay: '00:{{ states.sensor.tempo_cotrol_corredor.state }}:00'
    - service: light.turn_on
      entity_id: light.iluminacao_corredor
   
- alias: Controle Iluminação Cozinha
  trigger: 
    platform: state
    entity_id: light.iluminacao_cozinha
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 7
      seconds: 0
  condition:
    - condition: time
      after: '07:00:00'
      before: '19:00:00'
  action:
   service: light.turn_off
   entity_id: light.iluminacao_cozinha