- alias: 'Telegram bot1'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/cozinha'
  action:
    - service: notify.notifica_telegram
      data:
        message: 'pong'
        
- alias: Dona Home
  trigger:
    platform: state
    entity_id: device_tracker.s4
    from: 'not_home'
    to: 'home'
  action:
    service: notify.notifica_telegram
    data:
      message: Elida está em Casa
      
- alias: Dona Not Home
  trigger:
    platform: state
    entity_id: device_tracker.s4
    from: 'home'
    to: 'not_home'
  action:
    service: notify.notifica_telegram
    data:
      message: Elida saiu de Casa