#--------------------------------------------------------------------------

- alias: Localiza Dona
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/elida_loc'
  action:
    - service: notify.notifica_telegram
      data:
        message: "{% if is_state('device_tracker.s4', 'home') %} Elida está em Casa.\n{% else %} Elida não Está em Casa.\n{% endif %}"
        
#--------------------------------------------------------------------------

- alias: Localiza Denis
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/denis_loc'
  action:
    - service: notify.notifica_telegram
      data:
        message: "{% if is_state('device_tracker.leeco', 'home') %} Denis está em Casa.\n{% else %} Denis não Está em Casa.\n{% endif %}"

#--------------------------------------------------------------------------

# action:
#      service: script.turn_on
#      data_template:
#        entity_id: >-
#            {% if is_state("device_tracker.user", "home") %}
##              script.a
##            {% else %}
#              script.b
#            {% endif %}


- alias: Localizar Elida
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/loca_elida'
  action:
    service: script.turn_on
    data_template:
      entity_id: >-
        {% if is_state('device_tracker.s4', 'home') %}
           script.scr_loca_casa
        {% else %}
           script.scr_loca_not_casa
        {% endif%}
        
- alias: Localizar Denis
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/loca_denis'
  action:
    service: script.turn_on
    data_template:
      entity_id: >-
        {% if is_state('device_tracker.s4', 'home') %}
           script.scr_loca_casa2
        {% else %}
           script.scr_loca_not_casa2
        {% endif%}




- alias: Checa Localizacao Dona
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/dona_loc'
  action:
    - service: telegram_bot.send_location
      data:
        latitude: '{{states.device_tracker.elida_samsung.attributes.latitude}}'
        longitude: '{{states.device_tracker.elida_samsung.attributes.longitude}}'

#--------------------------------------------------------------------------
               
- alias: Temperatura Rasp
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/temp_rasp'
  action:
    - service: notify.notifica_telegram
      data:
        message: 'A temperatura do Raspberry é  {{states.sensor.cpu_temperature.state}} ºC'
        
#--------------------------------------------------------------------------
        
- alias: Temperatura Quarto Casal
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/temp_quarto_casal'
  action:
    - service: notify.notifica_telegram
      data:
        message: 'A Temperatura do Quarto Casal é  {{states.sensor.temperature_158d0001d6f829.state}} ºC'
        
#--------------------------------------------------------------------------  
      
- alias: Temperatura Sacada
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/temp_sacada'
  action:
    - service: notify.notifica_telegram
      data:
        message: 'A Temperatura da Sacada é  {{states.sensor.temperature_158d0001d82855.state}} ºC'
        
#--------------------------------------------------------------------------    
      
- alias: Temperatura Quarto Filho
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/temp_quarto_filho'
  action:
    - service: notify.notifica_telegram
      data:
        message: 'A Temperatura do Quarto do Filho é {{states.sensor.temperature_158d0001d82815.state}} ºC'
        
#--------------------------------------------------------------------------   
     
- alias: Temperatura Sala
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/temp_sala'
  action:
    - service: notify.notifica_telegram
      data:
        message: 'A Temperatura da Sala é {{states.sensor.temperature_158d00019c9488.state}} ºC'
        
#--------------------------------------------------------------------------
