#- alias: Let a dog bark on long press
#  trigger:
#    platform: event
#    event_type: click
#    event_data:
#      entity_id: binary_sensor.switch_158d00016d7b12
#      click_type: long_click_press
#  action:
#    service: xiaomi_aqara.play_ringtone
#    data:
#      gw_mac: 34CE00813667
#      ringtone_id: 1
#      ringtone_vol: 80

#- alias: Stop barking immediately on single click
#  trigger:
#    platform: event
#    event_type: click
#    event_data:
#      entity_id: binary_sensor.switch_158d00016d7b12
#      click_type: single
#  action:
#    service: xiaomi_aqara.stop_ringtone
#    data:
#      gw_mac: 34CE00813667
      
- alias: Acende Lampada Quarto Casal
  trigger:
    platform: event
    event_type: click
    event_data:
       entity_id: binary_sensor.switch_158d00016d7b12
       click_type: long_click_press
  action:
    service: light.turn_on
    entity_id: light.iluminacao_quarto_casal
    
- alias: Apaga Lampada Quarto Casal
  trigger:
    platform: event
    event_type: click
    event_data:
       entity_id: binary_sensor.switch_158d00016d7b12
       click_type: single
  action:
    service: light.turn_off
    entity_id: light.iluminacao_quarto_casal